// Generated by CoffeeScript 1.9.3
(function() {
  var spawn;

  spawn = require('child_process').spawn;

  module.exports = function(socket) {
    console.log('connwcted!');
    socket.emit('news', {
      hello: 'world'
    });
    socket.on('sync', function(data) {
      var ls;
      ls = spawn('ls', ['-lh', '/usr']);
      ls.stdout.on('data', function(data) {
        socket.emit('answer', data.toString());
        return console.log("stdout: " + data);
      });
      ls.stderr.on('data', function(data) {
        return console.log("stderr: " + data);
      });
      return ls.on('close', function(code) {
        socket.emit('sync-answer-done', data);
        return console.log("child process exited with code " + code);
      });
    });
    return socket.on('move-done-torrents', function(data) {
      var ls;
      ls = spawn('move-done-torrents.sh');
      ls.stdout.on('data', function(data) {
        socket.emit('answer', data.toString());
        return console.log("stdout: " + data);
      });
      ls.stderr.on('data', function(data) {
        return console.log("stderr: " + data);
      });
      return ls.on('close', function(code) {
        socket.emit('sync-answer-done', data);
        return console.log("child process exited with code " + code);
      });
    });
  };

}).call(this);

//# sourceMappingURL=socket.js.map
