// Generated by CoffeeScript 1.9.3
(function() {
  var spawn;

  spawn = require('child_process').spawn;

  module.exports = function(socket) {
    console.log('connwcted!');
    socket.emit('news', {
      hello: 'world'
    });
    socket.on('sync', function(data) {
      var sync;
      sync = spawn('acd_cli', ['sync']);
      sync.stdout.on('data', function(data) {
        socket.emit('answer', data.toString());
        return console.log("stdout: " + data);
      });
      sync.stderr.on('data', function(error) {
        socket.emit('error', error);
        return console.log("stderr: " + data);
      });
      return sync.on('close', function(code) {
        socket.emit('done', 'done');
        return console.log("child process exited with code " + code);
      });
    });
    return socket.on('move-done-torrents', function(data) {
      var move;
      move = spawn('./move-done-torrents.sh');
      move.stdout.on('data', function(data) {
        socket.emit('answer', data.toString());
        return console.log("stdout: " + data);
      });
      move.stderr.on('data', function(error) {
        socket.emit('error', error);
        return console.log("stderr: " + data);
      });
      return move.on('close', function(code) {
        socket.emit('done', 'done');
        return console.log("child process exited with code " + code);
      });
    });
  };

}).call(this);

//# sourceMappingURL=socket.js.map
